version: '0.1'
services:
  zookeeper: # отвечает за конфигурацию
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on: # запускаемся после zookeeper'а
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  es:
    image: elasticsearch:6.5.0
    container_name: es1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      http.host: 0.0.0.0
      network.host: 0.0.0.0
      transport.host: 127.0.0.1
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      ES_JAVA_OPTIONS: "-Xms1g -Xmx1g"

  # elasticsearch:
  #   container_name: elasticsearch1
  #   build:
  #     dockerfile: Dockerfile.elasticsearch
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   environment:
  #     - discovery.type=single-node
      # - http.host=0.0.0.0
      # - transport.host=127.0.0.1
      # - xpack.security.enabled=false
      # # - 'ES_JAVA_OPTIONS=-Xms1g -Xmx1g'
      # # - 'ES_JAVA_OPTS=-Xms1g -Xmx1g'
      # - "ES_JAVA_OPTIONS=-Xms512m -Xmx512m"
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # # - "ES_JAVA_OPTIONS=-Xms512m -Xmx512m"
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
