version: '0.1'
services:
  zookeeper: # отвечает за конфигурацию
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on: # запускаемся после zookeeper'а
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  connect:
    image: confluentinc/cp-kafka-connect:3.3.0
    container_name: kafka_connect
    ports:
      - 8083:8083
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - $PWD/connect-plugins:/connect-plugins
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "connect"
      CONNECT_CONFIG_STORAGE_TOPIC: connect-config
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_REPLICATION_FACTOR: 1
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
      CONNECT_REST_ADVERTISED_HOST_NAME: "connect"
      CONNECT_ZOOKEEPER_CONNECT: zookeeper:2181
      CONNECT_PLUGIN_PATH: /connect-plugins
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_LOG4J_LOGGERS: org.reflections=ERROR
      CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-3.3.0.jar

  elasticsearch:
    image: elasticsearch:6.5.0
    container_name: es1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      http.host: 0.0.0.0
      transport.host: 0.0.0.0
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      ES_JAVA_OPTIONS: "-Xms1g -Xmx1g"

  flask-server:
    container_name: flask-server
    build:
      context: ./flask_server
      dockerfile: ./Dockerfile
    ports:
      - 56733:80
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: development
    volumes:
      - ./flask_server:/app

  scrapyd:
    build:
      context: ./scrapyd
      dockerfile: ./Dockerfile
    container_name: scrapyd
    ports:
      - 6800:6800

  # elasticsearch:
  #   container_name: elasticsearch1
  #   build:
  #     dockerfile: Dockerfile.elasticsearch
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   environment:
  #     - discovery.type=single-node
      # - http.host=0.0.0.0
      # - transport.host=127.0.0.1
      # - xpack.security.enabled=false
      # # - 'ES_JAVA_OPTIONS=-Xms1g -Xmx1g'
      # # - 'ES_JAVA_OPTS=-Xms1g -Xmx1g'
      # - "ES_JAVA_OPTIONS=-Xms512m -Xmx512m"
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # # - "ES_JAVA_OPTIONS=-Xms512m -Xmx512m"
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
